title: gertybot
url: "https://gertybot.github.io"
baseurl: ""
author: Gerty

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - README.md
  - LICENSE
  - Gemfile
